CREATE TABLE garden (
  id                 VARCHAR(255),
  air_temperature    DOUBLE,
  mdate              VARCHAR(255),
  radiation          DOUBLE,
  relevant_humidity  DOUBLE,
  site               VARCHAR(255),
  sphere_temperature DOUBLE,
  wind_direction     DOUBLE,
  wind_speed         DOUBLE,
  PRIMARY KEY (id)
);

CREATE TABLE review (
  id            INTEGER,
  comments      VARCHAR(255),
  review_date   DATE,
  rating        INTEGER,
  reviewer_name VARCHAR(255),
  PRIMARY KEY (id)
);

CREATE TABLE sintagma (
  id                 VARCHAR(255),
  air_temperature    DOUBLE,
  mdate              VARCHAR(255),
  radiation          DOUBLE,
  relevant_humidity  DOUBLE,
  site               VARCHAR(255),
  sphere_temperature DOUBLE,
  wind_direction     DOUBLE,
  wind_speed         DOUBLE,
  PRIMARY KEY (id)
);
CREATE TABLE visitor (
  id             INTEGER,
  vdate          VARCHAR(255),
  day_of_week    VARCHAR(255),
  number_of_week INTEGER,
  serial_num     VARCHAR(255),
  site           VARCHAR(255),
  visitors       INTEGER,
  PRIMARY KEY (id)
);



INSERT INTO garden ( mdate,air_temperature, relevant_humidity, wind_direction, wind_speed, radiation,sphere_temperature)
VALUES ('26-07-2017  10:00:00 AM',	25.264,	55.64,	311.4,	0.2088	,0.6576,	0 );



INSERT INTO garden ( mdate,air_temperature, relevant_humidity, wind_direction, wind_speed, radiation,sphere_temperature)
VALUES ('7-26-17 10:10 AM',	25.376,53.716	,311.2,	0.2058,	0.6896,0);




INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0001-02-18', 'Thursday', 5, 554, 51);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0002-02-18', 'Friday', 5, 547, 52);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0003-02-18', 'Saturday', 5, 434, 53);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0004-02-18', 'Sunday', 5, 0, 54);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0005-02-18', 'Monday', 6, 548, 55);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0006-02-18', 'Tuesday', 6, 545, 56);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0007-02-18', 'Wednesday', 6, 421, 57);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0008-02-18', 'Thursday', 6, 467, 58);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0009-02-18', 'Friday', 6, 545, 59);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0010-02-18', 'Saturday', 6, 379, 60);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0011-02-18', 'Sunday', 6, 0, 61);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0012-02-18', 'Monday', 7, 490, 62);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0013-02-18', 'Tuesday', 7, 561, 63);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0014-02-18', 'Wednesday', 7, 394, 64);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0015-02-18', 'Thursday', 7, 281, 65);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0016-02-18', 'Friday', 7, 503, 66);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0017-02-18', 'Saturday', 7, 520, 67);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0018-02-18', 'Sunday', 7, 0, 68);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0019-02-18', 'Monday', 8, 0, 69);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0020-02-18', 'Tuesday', 8, 393, 70);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0021-02-18', 'Wednesday', 8, 411, 71);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0022-02-18', 'Thursday', 8, 504, 72);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0023-02-18', 'Friday', 8, 502, 73);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0024-02-18', 'Saturday', 8, 381, 74);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0025-02-18', 'Sunday', 8, 0, 75);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0026-02-18', 'Monday', 9, 350, 76);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0027-02-18', 'Tuesday', 9, 552, 77);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0028-02-18', 'Wednesday', 9, 434, 78);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0001-03-18', 'Thursday', 9, 523, 79);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0002-03-18', 'Friday', 9, 452, 80);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0003-03-18', 'Saturday', 9, 468, 81);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0004-03-18', 'Sunday', 9, 0, 82);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0005-03-18', 'Monday', 10, 468, 83);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0006-03-18', 'Tuesday', 10, 499, 84);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0007-03-18', 'Wednesday', 10, 420, 85);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0008-03-18', 'Thursday', 10, 532, 86);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0009-03-18', 'Friday', 10, 514, 87);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0010-03-18', 'Saturday', 10, 399, 88);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0011-03-18', 'Sunday', 10, 0, 89);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0012-03-18', 'Monday', 11, 399, 90);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0013-03-18', 'Tuesday', 11, 473, 91);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0014-03-18', 'Wednesday', 11, 382, 92);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0015-03-18', 'Thursday', 11, 435, 93);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0016-03-18', 'Friday', 11, 474, 94);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0017-03-18', 'Saturday', 11, 429, 95);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0018-03-18', 'Sunday', 11, 0, 96);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0019-03-18', 'Monday', 12, 415, 97);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0020-03-18', 'Tuesday', 12, 505, 98);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0021-03-18', 'Wednesday', 12, 388, 99);
INSERT INTO PUBLIC.VISITOR (SITE, SERIAL_NUM, VDATE, DAY_OF_WEEK, NUMBER_OF_WEEK, VISITORS, ID)
VALUES ('athinas', '', '0022-03-18', 'Thursday', 12, 304, 100);